export const Defaults = {
  ONE: 1,
  PAGE_LIMIT: 100,
  ZERO: 0,
  MINUS_ONE: -1,
  NOT_FOUND_STATUS_CODE: 404,
  READY_STATE: 1,
  CHUNK_SIZE: 100,
  DATE_FORMATS: ['DD/MM/YYYY'],
  DATE_FORMAT: 'DD/MM/YYYY',
};
