import Head from 'next/head';
import Image from 'next/image';
import getConfig from 'next/config';
import { PropsWithChildren, useRef } from 'react';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import TawkMessengerReact from '@tawk.to/tawk-messenger-react';
import { Flex, Group, LoadingOverlay, Select, Stack, Title, useMantineColorScheme } from '@mantine/core';

import { Import } from '@assets/icons';
import useStyles from './AppLayout.styles';
import LogoBlack from '@assets/images/Logo-black.svg';
import LogoWhite from '@assets/images/Logo-white.svg';
import { LogoutIcon } from '@assets/icons/Logout.icon';

import { CONSTANTS } from '@config';
import { useApp } from '@hooks/useApp';
import { NavItem } from '@ui/nav-item';
import { UserMenu } from '@ui/user-menu';
import { track } from '@libs/amplitude';
import { ColorSchemeToggle } from '@ui/toggle-color-scheme';

const { publicRuntimeConfig } = getConfig();

export function AppLayout({ children }: PropsWithChildren) {
  const twakRef = useRef<any>();
  const { classes } = useStyles();
  const navRef = useRef<HTMLElement>(null);
  const { colorScheme } = useMantineColorScheme();
  const { profile, projects, createProject, logout, setProjectId, isProjectsLoading } = useApp();

  return (
    <>
      <Head>
        <title>Web Portal for Impler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.root}>
        <LoadingOverlay visible={isProjectsLoading} />
        <aside className={classes.aside}>
          <div className={classes.logoContainer}>
            <Image src={colorScheme === 'dark' ? LogoWhite : LogoBlack} alt="Impler Logo" width={140} />
          </div>
          <Select
            data={projects?.map((project) => ({ label: project.name, value: project._id })) || []}
            placeholder="Select Project"
            nothingFound="No projects found"
            searchable
            creatable
            pl="sm"
            radius={0}
            value={profile?._projectId}
            getCreateLabel={(query) => `+ Create "${query}"`}
            onChange={(value: string) => setProjectId(value)}
            onCreate={(value: string) => {
              createProject({ name: value });

              return { value, label: value };
            }}
          />
          <Stack spacing="sm" py="xs">
            <NavItem active href="/imports" icon={<Import size="lg" />} title="Imports" />
          </Stack>
        </aside>
        <main className={classes.main}>
          <nav className={classes.nav} ref={navRef}>
            {profile && (
              <Flex justify="space-between">
                <Title order={2}>
                  Welcome, {profile.firstName} {profile.lastName}
                </Title>
                <Group>
                  <ColorSchemeToggle onChange={(theme) => track({ name: 'TOGGLE THEME', properties: { theme } })} />
                  <UserMenu
                    user={{
                      name: `${profile.firstName} ${profile.lastName}`,
                      email: profile.email,
                      image: profile.profilePicture,
                    }}
                    menus={[
                      {
                        title: 'Logout',
                        icon: <LogoutIcon />,
                        onClick: logout,
                      },
                    ]}
                  />
                </Group>
              </Flex>
            )}
          </nav>
          <div className={classes.content}>
            <div className={classes.contentBox}>{children}</div>
          </div>
        </main>
      </div>
      {publicRuntimeConfig.NEXT_PUBLIC_TAWK_PROPERTY_ID && publicRuntimeConfig.NEXT_PUBLIC_TAWK_WIDGET_ID ? (
        <TawkMessengerReact
          propertyId={publicRuntimeConfig.NEXT_PUBLIC_TAWK_PROPERTY_ID}
          widgetId={publicRuntimeConfig.NEXT_PUBLIC_TAWK_WIDGET_ID}
          ref={twakRef}
          onLoad={() => {
            if (typeof window !== 'undefined' && localStorage.getItem(CONSTANTS.PROFILE_STORAGE_NAME)) {
              const user = JSON.parse(localStorage.getItem(CONSTANTS.PROFILE_STORAGE_NAME)!);
              twakRef.current?.setAttributes({
                id: user._id,
                name: user.firstName,
                email: user.email,
              });
            }
          }}
        />
      ) : null}
    </>
  );
}
