import Head from 'next/head';
import Image from 'next/image';
import { PropsWithChildren, useRef } from 'react';
import { Flex, Group, Select, Stack, Title, useMantineColorScheme } from '@mantine/core';

import { Import } from '@assets/icons';
import useStyles from './AppLayout.styles';
import LogoBlack from '@assets/images/Logo-black.svg';
import LogoWhite from '@assets/images/Logo-white.svg';
import { LogoutIcon } from '@assets/icons/Logout.icon';

import { useApp } from '@hooks/useApp';
import { NavItem } from '@ui/nav-item';
import { UserMenu } from '@ui/user-menu';
import { ColorSchemeToggle } from '@ui/toggle-color-scheme';

export function AppLayout({ children }: PropsWithChildren) {
  const { classes } = useStyles();
  const navRef = useRef<HTMLElement>(null);
  const { profile, projects, createProject, projectId, setProjectId, logout } = useApp();
  const { colorScheme } = useMantineColorScheme();

  return (
    <>
      <Head>
        <title>Web Portal for Impler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.root}>
        <aside className={classes.aside}>
          <div className={classes.logoContainer}>
            <Image src={colorScheme === 'dark' ? LogoWhite : LogoBlack} alt="Impler Logo" width={140} />
          </div>
          <Select
            data={projects?.map((project) => ({ label: project.name, value: project._id })) || []}
            placeholder="Select Project"
            nothingFound="No projects found"
            searchable
            creatable
            pl="sm"
            radius={0}
            value={projectId}
            getCreateLabel={(query) => `+ Create "${query}"`}
            onChange={(value: string) => setProjectId(value)}
            onCreate={(value: string) => {
              createProject({ name: value });

              return { value, label: value };
            }}
          />
          <Stack spacing="sm" py="xs">
            <NavItem active href="/imports" icon={<Import size="lg" />} title="Imports" />
          </Stack>
        </aside>
        <main className={classes.main}>
          <nav className={classes.nav} ref={navRef}>
            {profile && (
              <Flex justify="space-between">
                <Title order={2}>
                  Welcome, {profile.firstName} {profile.lastName}
                </Title>
                <Group>
                  <ColorSchemeToggle />
                  <UserMenu
                    user={{
                      name: `${profile.firstName} ${profile.lastName}`,
                      email: profile.email,
                      image: profile.profilePicture,
                    }}
                    menus={[
                      {
                        title: 'Logout',
                        icon: <LogoutIcon />,
                        onClick: logout,
                      },
                    ]}
                  />
                </Group>
              </Flex>
            )}
          </nav>
          <div className={classes.content}>
            <div className={classes.contentBox}>{children}</div>
          </div>
        </main>
      </div>
    </>
  );
}
