// eslint-disable-next-line @typescript-eslint/naming-convention
export enum AVAILABLE_BILLABLEMETRIC_CODE_ENUM {
  IMPORTED_ROWS = 'IMPORTED_ROWS',
  REMOVE_BRANDING = 'REMOVE_BRANDING',
  IMAGE_IMPORT = 'IMAGE_IMPORT',
  ADVANCED_VALIDATORS = 'ADVANCED_VALIDATORS',
}
