// eslint-disable-next-line @typescript-eslint/naming-convention
export enum AVAILABLE_BILLABLEMETRIC_CODE_ENUM {
  ROWS = 'ROWS',
  IMPORTED_ROWS = 'IMPORTED_ROWS',
  REMOVE_BRANDING = 'REMOVE_BRANDING',
  IMAGE_IMPORT = 'IMAGE_IMPORT',
  ADVANCED_VALIDATORS = 'ADVANCED_VALIDATORS',
  TEAM_MEMBERS = 'TEAM_MEMBERS',
  AUTOMATIC_IMPORTS = 'AUTOMATIC_IMPORTS',
  FREEZE_COLUMNS = 'FREEZE_COLUMNS',
}
