export const WIDGET_READY = 'WIDGET_READY';
export const INIT_IFRAME = 'INIT_IFRAME';

export const SHOW_WIDGET = 'SHOW_WIDGET';

export const CLOSE_WIDGET = 'CLOSE_WIDGET';
export const AUTHENTICATION_VALID = 'AUTHENTICATION_VALID';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
