import Head from 'next/head';
import Image from 'next/image';
import { useRef } from 'react';
import { Flex, Group, Select, Stack, Title, useMantineColorScheme, useMantineTheme } from '@mantine/core';

import { Import } from '@assets/icons';
import LogoBlack from '@assets/images/Logo-black.svg';
import LogoWhite from '@assets/images/Logo-white.svg';
import { LogoutIcon } from '@assets/icons/Logout.icon';

import { colors } from '@config';
import { NavItem } from '@ui/nav-item';
import { UserMenu } from '@ui/user-menu';
import { ColorSchemeToggle } from '@ui/toggle-color-scheme';

export function AppLayout({ children }: any) {
  const navRef = useRef<HTMLElement>(null);
  const theme = useMantineTheme();
  const { colorScheme } = useMantineColorScheme();

  return (
    <>
      <Head>
        <title>Web Portal for Impler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: '100vh', display: 'flex' }}>
        <aside style={{ width: 'calc(100vw - 85%)', minWidth: '150px' }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              paddingBlock: theme.spacing.lg,
              paddingLeft: theme.spacing.md,
            }}
          >
            <Image src={colorScheme === 'dark' ? LogoWhite : LogoBlack} alt="Impler Logo" width={140} />
          </div>
          <Select
            data={[
              { value: 'project1', label: 'Project 1' },
              { value: 'project2', label: 'Project 2' },
            ]}
            placeholder="Select items"
            nothingFound="Nothing found"
            searchable
            creatable
            pl="sm"
            radius={0}
            getCreateLabel={(query) => `+ Create ${query}`}
          />
          <Stack spacing="sm" py="xs">
            <NavItem active href="/imports" icon={<Import size="lg" />} title="Imports" />
          </Stack>
        </aside>
        <main style={{ width: '100%', padding: theme.spacing.lg, display: 'flex', flexDirection: 'column' }}>
          <nav style={{ alignItems: 'center' }} ref={navRef}>
            <Flex justify="space-between">
              <Title order={2}>Welcome, John Doe</Title>
              <Group>
                <ColorSchemeToggle />
                <UserMenu
                  user={{
                    name: 'John Doe',
                    email: 'johndoe@ggmail.com',
                    image: 'https://avatars.githubusercontent.com/u/25126261?v=4',
                  }}
                  menus={[
                    {
                      title: 'Logout',
                      icon: <LogoutIcon />,
                    },
                  ]}
                />
              </Group>
            </Flex>
          </nav>
          <div style={{ paddingTop: theme.spacing.md, flexGrow: 1 }}>
            <div
              style={{
                backgroundColor: colorScheme === 'dark' ? colors.BGSecondaryDark : colors.BGSecondaryLight,
                width: '100%',
                height: '100%',
                borderRadius: theme.radius.lg,
                padding: theme.spacing.lg,
              }}
            >
              {children}
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
